import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

const barlow = Barlow({
  weight: '400',
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlow.className}>{children}</body>
    </html>
  );
}
